# Generated by Django 5.2.6 on 2025-09-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_level_m', models.FloatField(verbose_name='Water Level (m)')),
                ('temperature_c', models.FloatField(verbose_name='Temperature (°C)')),
                ('rainfall_mm', models.FloatField(verbose_name='Rainfall (mm)')),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='pH')),
                ('dissolved_oxygen_mg_l', models.FloatField(verbose_name='Dissolved Oxygen (mg/L)')),
            ],
        ),
    ]
