# Generated by Django 4.2.30 on 2026-08-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwlr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterqualityrecord',
            name='lat',
            field=models.FloatField(default=28.6139),
        ),
        migrations.AddField(
            model_name='waterqualityrecord',
            name='lon',
            field=models.FloatField(default=77.209),
        ),
        migrations.AddField(
            model_name='waterqualityrecord',
            name='station_id',
            field=models.CharField(default='DWLR-001', max_length=20),
        ),
    ]
